### ISSUE TITLE
Readapt the Screens with the new wireframes

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-workspace#10]
Create the screens of the application according with the wireframes

PRIORITY:
1. Replace the coluum "last ICF status" with the coloum "TP status" as in the attached image
![image_2021_04_29T08_13_21_454Z](https://user-images.githubusercontent.com/58935926/116526803-ab015a80-a8e2-11eb-81d4-ba02da8e0c53.png)

**Comment by anastath** [comment]
TO-DO:: Prioritise the screens and then either discuss with Fotis or with Ana
