### ISSUE TITLE
When adding a site consent please send in the message only siteUid and econsent uid

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-workspace#154]

**Comment by Mastaleru** [comment]
only siteUid for new econsent
ssi:siteUid and econsnetUid:econsentUid for new version

**Comment by Desouler** [comment]
This has already be done, correct?
on new econsent message contains: ssi: site.uid

on new version message contains: ssi: site.uid, econsentUid: econsent.uid
