### ISSUE TITLE
Implement Personalized Feedback (ask for mock data)

### ISSUE THREAD

**Issue by Mastaleru** [PharmaLedger-IMI/eco-workspace#174]
![image](https://user-images.githubusercontent.com/1469129/166639673-ad4dcfab-a845-4ef0-841f-9ae482257681.png)

**Comment by Mastaleru** [comment]
@Ana-ui ask for mock data

**Comment by cosmintuca** [comment]
The Feedback page, as discussed, should be now in Health Studies -> Completed Studies -> Feedback button
