### ISSUE TITLE
Rename the 'eDiary' page with 'Tasks Calendar' and redesign the page as in the attached mockups

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-workspace#184]
![image](https://user-images.githubusercontent.com/58935926/168251845-88b6541b-7d8a-4e17-993d-628bb2a55033.png)
![image](https://user-images.githubusercontent.com/58935926/168251710-524ac79a-3668-40ac-a0bb-9b7aa3a52517.png)

**Comment by Mastaleru** [comment]
already fixed
