### ISSUE TITLE
Save Patient permission to share data

### ISSUE THREAD

**Issue by Ana-ui** [PharmaLedger-IMI/eco-workspace#193]
When patient agrees on sharing the data, the permission and data should be saved as long as the answers is yes and should  be withrawn as soon as the patient answer is no
no
![image](https://user-images.githubusercontent.com/58935926/170528226-c05606ee-e3f2-4e51-87d9-ce28d424e5bb.png)

**Comment by Mastaleru** [comment]
already finished
